# Generated by Django 5.1.5 on 2025-02-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='full_info',
            field=models.TextField(null=True),
        ),
    ]
